[Nngs]

Host = 'localhost'

# 接続先サーバーのポート番号
# (^q^) 数値型のデータをクォーテーションで囲むとエラーもなく読取失敗するから注意☆
Port = 9696

# 対局者名（アカウント名）
# Only A-Z a-z 0-9
# Names may be at most 10 characters long
User = 'Kifuwarabe'

# パスワード（任意）
Pass = ''

# マッチの申込
[MatchApplication]

# 白番なら 'W', 黒番なら 'B'
Phase = 'W'

# 何路盤
BoardSize = 19

# 持ち時間（分）
AvailableTimeMinutes = 40

# カナダ式秒読み。25手を何分以内に打てばよいか
CanadianTiming = 0
