[Nngs]

# * `Human` - 人間プレイヤーが接続する
# * `GTP` - GTP(碁テキスト プロトコル)を用いる思考エンジンが接続する
PlayerType = 'GTP'

Host = 'localhost'

# 接続先サーバーのポート番号
# (^q^) 数値型のデータをクォーテーションで囲むとエラーもなく読取失敗するから注意☆
Port = 9696

# 対局者名（アカウント名）
# Only A-Z a-z 0-9
# Names may be at most 10 characters long
User = 'Kifuwarabi'

# パスワード（任意）
Pass = ''

# マッチの申込
[MatchApplication]

# 自分の方から申し込むなら true, 申し込みを受けるのを待つ方なら false。
# true にしたなら、 Opponent も設定してください
Apply = true

# 自分の方から申し込むなら、対戦相手のアカウント名も指定してください。そうでないなら無視されます
Opponent = "Kifuwarabe"

# 白番なら 'W', 黒番なら 'B'
Phase = 'B'

# 何路盤
BoardSize = 19

# 持ち時間（分）
AvailableTimeMinutes = 40

# カナダ式秒読み。25手を何分以内に打てばよいか
CanadianTiming = 0
