[Nngs]

Server = 'localhost'
# (^q^) 数値型のデータをクォーテーションで囲むとエラーもなく読取失敗するから注意☆
Port = 9696
User = 'Kifuwarabe_UEC12_w' # your account
Pass = '' # your password (any)

# マッチの申込
[ApplyForAMatch]

# 白番なら 'W', 黒番なら 'B'
Phase = 'W'

# 何路盤
BoardSize = 19

# 持ち時間（分）
AvailableTimeMinutes = 40

# カナダ式秒読み。25手を何分以内に打てばよいか
CanadianTiming = 0
